# Generated by Django 4.1 on 2022-12-19 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('institucion', models.CharField(max_length=50)),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('reservado', 'RESERVADO'), ('completada', 'COMPLETADA'), ('anulada', 'ANULADA'), ('no asisten', 'NO ASISTEN')], default='reservado', max_length=10)),
                ('observaciones', models.CharField(max_length=100)),
            ],
        ),
    ]
